wallpaper {
    monitor = DP-1
    path = /home/devc4rlos/Downloads/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/devc4rlos/Downloads/wallpaper.jpg
    fit_mode = cover
}